### ISSUE TITLE
about the op in model.py

### ISSUE THREAD

**Issue by Deepseabro** [ch10tang/stylegan2-based-face-frontalization#1]
I try to train the network but there is something wrong.
Traceback (most recent call last):
  File "/home/ff/ZHL/stylegan2-based-face-frontalization-main/train.py", line 29, in <module>
    from model import Generator, Discriminator
  File "/home/ff/ZHL/stylegan2-based-face-frontalization-main/model.py", line 12, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
ModuleNotFoundError: No module named 'op'
I can not find where is the op.
thanks!

**Comment by ch10tang** [comment]
I have uploaded the "/op/" file into the repository. 
Thanks for your friendly reminder.

**Comment by hui-vigil** [comment]
In the /op/ folder, updirdn2d and FusedLeakyReLUFunction or other class have no method "apply", but only forward and backward, so if the method "apply"  is wrong or other case, could you check it， thank you
